### ISSUE TITLE
Undefined array key "took"

### ISSUE THREAD

**Issue by Fossil01** [manticoresoftware/manticoresearch-php#117] opened 2023-04-06 19:09 UTC
Getting these seemingly randomly. Any ideas?      
      
```      
  Undefined array key "took"      
      
  at vendor/manticoresoftware/manticoresearch-php/src/Manticoresearch/ResultSet.php:48      
     44▕             $this->total = $response['hits']['total'];      
     45▕         } else {      
     46▕             $this->total = 0;      
     47▕         }      
  ➜  48▕         $this->took = $response['took'];      
     49▕         $this->timed_out = $response['timed_out'];      
     50▕         if (isset($response['profile'])) {      
     51▕             $this->profile = $response['profile'];      
     52▕         }      
      
       2 vendor frames      
```

**Comment by sanikolaev** [comment] 2023-04-07 06:34
Does this happen for a specific query or the same query randomly results in this error?

**Comment by sanikolaev** [comment] 2023-04-11 08:07
Thanks, we'll look into this.

**Comment by githubmanticore** [comment] 2023-04-20 07:41
➤ Nick Sergeev commented:
 

 
Unfortunately, we haven't been able to reproduce this error. Can you please specify your client and Manticore versions?   
Also, it would be great if you could provide a minimal example from your app's code to reproduce the issue.

**Comment by genby8** [comment] 2023-04-25 11:51
```
$index->create([ 
	'title'=>['type'=>'text'], 
	'year'=>['type'=>'integer'], 
]); 
$search = new \Manticoresearch\Search($client); 
$bool = new BoolQuery();
$bool->must(new Equals('year', '2000'));
$results = $search->search($bool)->get();
```
year type integer, but in query type string => "took"

**Comment by githubmanticore** [comment] 2023-04-26 09:18
➤ Nick Sergeev commented:
 

 
That's strange. In our tests, again, either ResponseException is thrown or all the Response fields are returned, 'took' included. 
Can you please execute the same code as below and see what result it returns? 
 
``` 
$config = ['host'=>'127.0.0.1','port'=>9408]; 
$client = new \Manticoresearch\Client($config); 
 
$index = $client->index('test'); 
 
$index->create([ 
	'title'=>['type'=>'text'], 
	'year'=>['type'=>'integer'], 
]); 
 
$search = new \Manticoresearch\Search($client); 
$bool = new \Manticoresearch\Query\BoolQuery(); 
$bool->must(new \Manticoresearch\Query\Equals('year', '2000')); 
$results = $search->search($bool)->get(); 
 
var_export($results);

**Comment by sanikolaev** [comment] 2023-05-02 09:47
@genby8 Hi. Is there any news on this?

**Comment by someson** [comment] 2023-07-05 10:06
`ResultSet::$response` array keys probably may not exist. The problem is, that if in some point you changes the backend code and frontend's still running, which causes the bug/feature above.

**Comment by githubmanticore** [comment] 2023-07-24 07:51
➤ Nick Sergeev commented:
 

 
Fixed in https://github.com/manticoresoftware/manticoresearch-php/commit/732e6dc202bfb359351241dfda7803ba779fda3c

**Closed by githubmanticore** 2023-07-24 07:51 UTC
Labels: bug
