### ISSUE TITLE
Float encoding problem

### ISSUE THREAD

**Issue by tinigin** [manticoresoftware/manticoresearch-php#185] opened 2024-01-11 09:55 UTC
In the range request I specify lte = 15.0, but the request sends 15. As an example of a request log:

{"index":"products","query":{"bool":{"must":[{"bool":{"must":{"equals":{"exp_category_id":1}}}}, {"range":{"search_data.properties.prop_5":{"lte":15}}}]}},"limit":0,"expressions":{"exp_category_id":"IN(category_id,51,52 ,53,54,55,56,57,58,59,60,61,62,63,64,65)"}}

I think the problem is that when encoding a data array, the json_encode function is used without the JSON_PRESERVE_ZERO_FRACTION parameter.

For this reason, requests are not executed very correctly.

There is a huge difference in queries with and without a dot, as example:

SELECT id, search_data.properties.prop_5 FROM products WHERE search_data.properties.prop_5 <= 1;
+------+------------------------------+
| id | search_data.properties.prop_5 |
+------+------------------------------+
| 320 | 1.450000 |
| 493 | 1.500000 |
| 427 | 1.600000 |
| 500 | 0.500000 |
| 483 | 0.500000 |
+------+------------------------------+

SELECT id, search_data.properties.prop_5 FROM products WHERE search_data.properties.prop_5 <= 1.0;
+------+------------------------------+
| id | search_data.properties.prop_5 |
+------+------------------------------+
| 500 | 0.500000 |
| 483 | 0.500000 |
+------+------------------------------+

Thanks!

**Comment by sanikolaev** [comment] 2024-01-11 11:28
Thanks for reporting this, @tinigin 

We'll look into this. If you want to make a PR with the fix, feel free to do it.

**Comment by Nick-S-2018** [comment] 2024-01-12 12:35
Obviously, this issue is caused by a bug on the server side, so we've opened a new [issue](https://github.com/manticoresoftware/manticoresearch/issues/1724) about it and closed this one.

**Closed by Nick-S-2018** 2024-01-12 12:35 UTC
Labels: bug, est::size_S
